### ISSUE TITLE
How to change default time for backuping

### ISSUE THREAD

**Issue by timur-orudzhov** [kartoza/docker-pg-backup#17]
In the docs i can't find a way for changing default time for backuping. Am missing something or it can't be changed?

**Comment by NyakudyaA** [comment]
There is currently no way to change that. It currently creates a backup at 11pm.
 If you want to improve this aspect you can look at backup.cron and build with your custom time or alternatively do a PR where you introduce a environment variable to manage that

**Comment by androane** [comment]
@NyakudyaA where is this *backup.cron*? I could only find the cronjobs in */etc/cron.d/backups-cron*

**Comment by NyakudyaA** [comment]
@androane yes meant that one.
