### ISSUE TITLE
Incorrect env variables names

### ISSUE THREAD

**Issue by androane** [kartoza/docker-pg-backup#18]
`pgenv.sh` has
```
export PGUSER=docker
export PGPASSWORD=docker
export PGPORT=5432
export PGHOST=db
export PGDATABASE=gis
export DUMPPREFIX=PG
export ARCHIVE_FILENAME=
```
while the documentation has other variable names

**Comment by NyakudyaA** [comment]
@androane look at `start.sh` you will see the environment variables being used there

**Comment by androane** [comment]
@NyakudyaA yes. What I'm trying to say is that there's a mismatch between those names and the ones in the doc (ex *PGUSER* vs *POSTGRES_USER*)

**Comment by NyakudyaA** [comment]
@androane I do not see them perhaps you can point me on the correct line where there is a mismatch.
The best way for you would be to fix the issues and we can look at your PR and happily merge

**Comment by androane** [comment]
Depending on what you want to change. The docs or the basecode :)

Readme: https://github.com/kartoza/docker-pg-backup#specifying-environment
In start.sh: https://github.com/kartoza/docker-pg-backup/blob/master/start.sh#L42

Note that the ones in **start.sh** are like **PGUSER**. In the README, there's **POSTGRES_USER**, which is not being used at all in **start.sh**.

**Comment by NyakudyaA** [comment]
@androane You can change the script `start.sh` to match the environment variables in the doc. Thanks for picking it up

**Comment by androane** [comment]
@NyakudyaA why not the other way around?

**Comment by NyakudyaA** [comment]
@androane  Because this image inherits from the `kartoza/postgis:version` so anything changed should apply directly to upstream images

**Comment by androane** [comment]
@NyakudyaA can't push branch because of permissions. Would like to open a PR

**Comment by NyakudyaA** [comment]
@androane just do a PR and I will review it and merge

**Comment by androane** [comment]
@NyakudyaA would like to create a PR, but can't push my local branch

**Comment by NyakudyaA** [comment]
@androane give me the URL of your branch

**Comment by androane** [comment]
@NyakudyaA are we talking different languages?
I cloned the repo. I created a local new branch. I did the changes. Now I'm trying to push the branch to your repo so I can open a PR. But I don't have permission. So what URL do you want ??

**Comment by NyakudyaA** [comment]
@androane 
That is not how you should be doing it. 
* Fork this repository so that it exists in your own credentials
![fork](https://user-images.githubusercontent.com/2510900/59416288-60959400-8dc5-11e9-9f98-0f9929584663.png)

* Clone your local copy of the repository
ie `git clone https://github.com/NyakudyaA/docker-pg-backup.git`

* Create a branch in your local environment
* Push your changes into your local branch 
* Create a pull request
![pull](https://user-images.githubusercontent.com/2510900/59416474-b66a3c00-8dc5-11e9-8592-4edcff8cf66c.png)
 using the UI in github

**Comment by androane** [comment]
Done

**Comment by NyakudyaA** [comment]
thanks @androane I will take a look and test

**Comment by androane** [comment]
@NyakudyaA will this be done soon? I need it and I was wondering if I should use my fork or wait for your update. Thanks!

**Comment by NyakudyaA** [comment]
Hi @androane I will merge soon and push a new image

**Comment by androane** [comment]
@NyakudyaA when I pull your image from dockerhub, it's still not working. Perhaps that image is not updated? It's looking at all *PG* prefixes env variables, instead of *POSTGRES_*. Haven't tried yet, but most probably it works if I ony clone the repo due to the latest fix

**Comment by NyakudyaA** [comment]
@androane You can clone the repo and build it , I am still waiting for permission to push to that specific repo in docker hub

**Comment by androane** [comment]
any news on updating the image in dockerhub? I'd really need it :)

**Comment by NyakudyaA** [comment]
Done in dockerhub
