### ISSUE TITLE
Latest tag not corresponding to latest version

### ISSUE THREAD

**Issue by slhck** [kartoza/docker-pg-backup#27]
The `latest` tag on Docker Hub was created two years ago.

Please update to 12.0.

**Comment by NyakudyaA** [comment]
> The `latest` tag on Docker Hub was created two years ago.
> 
> Please update to 12.0.

We already have the 12.0 please do `docker pull kartoza/docker-pg-backup:12.0`

**Comment by slhck** [comment]
Yes, but the `latest` tag is pointing to something older, or was this kept behind on purpose?

**Comment by NyakudyaA** [comment]
> Yes, but the `latest` tag is pointing to something older, or was this kept behind on purpose?

I will push it, I completely forgot about it when I tagged the 12.0

**Comment by slhck** [comment]
Awesome, thanks!
