### ISSUE TITLE
POSTGRES_PASS_FILE

### ISSUE THREAD

**Issue by lucbas** [kartoza/docker-pg-backup#28]
Hi all

Thanks for the great repos!

I'm trying to setup postgres and postgres-backup and was wondering if postgres-backup also supports `POSTGRES_PASS_FILE` environment command to set a secret.

Kind regards

**Comment by NyakudyaA** [comment]
@lucbas ideally it should. The image inherits from our upstream docker postgis.

**Comment by lucbas** [comment]
Thanks! I’m going to test and ket you know
