### ISSUE TITLE
backups-cron lets it run every minute

### ISSUE THREAD

**Issue by Leinad7331** [kartoza/docker-pg-backup#37]
Deploying the imgae (even with environment variables) deploys the backups-cron so that it backups every minute.

I had to manually enter the container and change the "backups-cron" file so that it only runs at 23h.

Is this the supposed behaviour or is there some kind of env-variable that I am missing?

It would be great if the container works out of the box with no manual configuration after starting it.

**Comment by NyakudyaA** [comment]
Hi, @Leinad7331 What version of the image are you running. I usually run it minutely when I am testing. If this is the behavior then I will fix it asap

**Comment by Leinad7331** [comment]
I am running 12:0. When I entered the docker container, ran nano on backups-cron I saw this:
![image](https://user-images.githubusercontent.com/52128264/100239552-d3e78300-2f31-11eb-9769-15d5e733ac54.png)

Commenting the first cron-job solved the issue for me.

**Comment by NyakudyaA** [comment]
> I am running 12:0. When I entered the docker container, ran nano on backups-cron I saw this:
> ![image](https://user-images.githubusercontent.com/52128264/100239552-d3e78300-2f31-11eb-9769-15d5e733ac54.png)
> 
> Commenting the first cron-job solved the issue for me.

Thanks, will take a look and fix

**Comment by NyakudyaA** [comment]
Added an env variable to control this
