### ISSUE TITLE
the cron schedule never executed

### ISSUE THREAD

**Issue by npltr62** [kartoza/docker-pg-backup#39]
Hi,
when i m executing manually this command `sudo docker exec dbbackups /backup-scripts/backups.sh` the dump file is created
but the cron schedule is not executed every night , why?
![image](https://user-images.githubusercontent.com/40625762/111189470-66319680-85b6-11eb-868c-9e2e9995625c.png)
is a problem with "users" => postgres/docker?

**Comment by NyakudyaA** [comment]
@npltr62 can you check what is contained in the crontab, will investigate this

**Comment by npltr62** [comment]
> @npltr62 can you check what is contained in the crontab, will investigate this

here is a screeshot of the crontab when i run vim

![image](https://user-images.githubusercontent.com/40625762/111282941-d4ba3700-863e-11eb-97b6-19f8311fea0f.png)

**Comment by NyakudyaA** [comment]
@npltr62 The /backups.sh should be /backup-scripts/backups.sh that's why it is not working. What image version are you using

**Comment by npltr62** [comment]
ok thanks
kartoza/postgis:13-3.1
kartoza/pg-backup:13.0

**Comment by npltr62** [comment]
i changed the above path in backups-cron but it's still not working,
should i change postgis image version? 13-3.1 => 13.0
