### ISSUE TITLE
File pgenv.sh not created, doesn't backup.

### ISSUE THREAD

**Issue by itsjef** [kartoza/docker-pg-backup#4]
Hi,

I am having an issue trying to automate backing up my database using your method. 

I edited `backups-cron` for it to run every 1 minute and ran `docker-compose up dbbackup`.

![](http://i.imgur.com/l10CvEx.png)

After awhile I came to check just to discover no .dmp were created :frowning: so I ran:

```
docker-compose run dbbackup /bin/bash
```

And found no `pgenv.sh` were created. Which is weird because the **log** from above did printed out all environment parameters specified in start.sh

![](http://i.imgur.com/O6soIBZ.png)

Then I manually ran `./start.sh` and waited for a while. The `pgenv.sh` was created then but still no `.dmp` in the backups directory :frowning: 

![](http://i.imgur.com/0htAAyB.png)

Only running `backups.sh` manually resulted in a .dmp

**Comment by NyakudyaA** [comment]
@itsjef In your docker-compose overwrite the entry point with the `start.sh` again and see if it helps

**Comment by itsjef** [comment]
> @itsjef In your docker-compose overwrite the entry point with the `start.sh` again and see if it helps

It's been almost 3 years now, I forgot what I tried to do back then :joy:

**Comment by NyakudyaA** [comment]
Fixed, working
