### ISSUE TITLE
S3 cleaner, awk syntax error

### ISSUE THREAD

**Issue by prevostc** [kartoza/docker-pg-backup#40]
Hello, thank you for your amazing container ^^

I just can't make the S3 cleaner to work, it seems that `awk {'print ${S3_BUCKET}" "${DEL_DAYS}'}` is a syntax error, playing manually with the command I believe this works: `awk '{print $S3_BUCKET" "$DEL_DAYS}'`

Regards

**Comment by NyakudyaA** [comment]
Thanks @prevostc can you do a PR with the fix

**Comment by prevostc** [comment]
Sure, let me know if that's an ok fix :)
