### ISSUE TITLE
No license in this project

### ISSUE THREAD

**Issue by legkvla** [kartoza/docker-pg-backup#45]
Hi all and thanks for great repo!

Are there any plans to add license to this repo?
https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

**Comment by NyakudyaA** [comment]
Hi, @legkvla Yes, we need to add the same licence as https://github.com/kartoza/docker-postgis/blob/develop/LICENSE. You can add this one to this and do a PR

**Comment by legkvla** [comment]
Thank you! Will do!

**Comment by legkvla** [comment]
License has been included to this PR:
https://github.com/kartoza/docker-pg-backup/pull/46
