### ISSUE TITLE
kartoza/pg-backup:13-3.1 doesn't exit (manifest unknown)

### ISSUE THREAD

**Issue by amq** [kartoza/docker-pg-backup#55]
Even though the `13-3.1` tag is explicitly mentioned in readme, it doesn't exist (anymore):
> We highly suggest that you use a tagged image that match the PostgreSQL image you are running i.e (kartoza/pg-backup:13-3.1 for backing up kartoza/postgis:13-3.1 DB). The latest tag may change and may not successfully back up your database.

**Comment by NyakudyaA** [comment]
Now available
