### ISSUE TITLE
Any plans on deploying the linux/arm64 to docker hub?

### ISSUE THREAD

**Issue by yousufctec** [kartoza/docker-pg-backup#58]
I was using the kartoza/postgis arm64 version, and wanted this backup image as well in arm64. Right now I'm building my own image for backup purposes which takes quite sometime, would be helpful and align with postgis.

Thanks!

**Comment by NyakudyaA** [comment]
Hi, We will when we get a chance but maybe you could start a PR to incorporate workflows into here by getting the logic from postgis repo

**Comment by DPR1604** [comment]
> Hi, We will when we get a chance but maybe you could start a PR to incorporate workflows into here by getting the logic from postgis repo

@NyakudyaA I know this is an older thread now but I wouldn't mind getting this logic implemented as I currently have a use case for this would you be able to point me to where this logic is in the kartoza/postgis so I can take a look?

**Comment by NyakudyaA** [comment]
Please check https://github.com/kartoza/docker-postgis/tree/develop/.github
That needs to be ported here and also just remove the scenario checks available otherwise the rest of the logic stays the same

**Comment by NyakudyaA** [comment]
Should be sorted now
