### ISSUE TITLE
Unreliable DBLIST generation

### ISSUE THREAD

**Issue by hylkevds** [kartoza/docker-pg-backup#64]
When the database is not ready at the time the docker-pg-backup container starts, it initialises with an empty DBLIST and thus never makes any backups.
If DBLIST is empty, it's probably better to exit with an error, so the container is restarted after a bit of a delay.

**Comment by NyakudyaA** [comment]
@hylkevds Can you test the PR

**Comment by hylkevds** [comment]
Tested, and can confirm it works.
Thanks for the fix!
