### ISSUE TITLE
restoring backup from s3

### ISSUE THREAD

**Issue by klibr007** [kartoza/docker-pg-backup#66]
Hey I read the github readme and the script used for back up and I dont really understand if it works if your backup is in an s3 object storage. You didn't mention it anywhere

**Comment by NyakudyaA** [comment]
> Hey I read the github readme and the script used for back up and I dont really understand if it works if your backup is in an s3 object storage. You didn't mention it anywhere

We haven't tried this so that's why it's not mentioned but a quick google search shows the following https://stackoverflow.com/questions/36090985/how-to-restore-postgres-dump-with-rds

**Comment by klibr007** [comment]
Thank you
