### ISSUE TITLE
Run as non-root

### ISSUE THREAD

**Issue by phertweck** [kartoza/docker-pg-backup#68]
Currently, the process in the container is running as root-user. Due to security reasons this is not recommended and even not easily possible in some environments (e.g. openShift).

I [tried](https://github.com/phertweck/docker-pg-backup/commit/e8002f4049e0a59b427d96c53c3d3fa6ef04078e) to add a new user and change the corresponding permissions.
Unfortunately it still fails with the following error message:

> cron: can't open or create /var/run/crond.pid: Permission denied

I didn't find any solution how to solve the permission issue with cron. Does anybody have an idea?

**Comment by NyakudyaA** [comment]
Unfortunately, the base image used kartoza/docker-postgis which has the same issue https://github.com/kartoza/docker-postgis/issues/245. We haven't invested much time in solving this, but I urge you to give it a go. Maybe try running it with gosu ?
