### ISSUE TITLE
no option to run backup once

### ISSUE THREAD

**Issue by troyliu0105** [kartoza/docker-pg-backup#76]
Thanks for this amazing work!!!
but I noticed that it seems no way to skip the built-in cron schedule. in k8s, we have cronjob controller to schedule job, to run & exit. And I think if there is a `RUN_ONCE` would be better, more friendly to k8s.

**Comment by NyakudyaA** [comment]
@troyliu0105 Does the associated PR fix this issue for you ?

**Comment by troyliu0105** [comment]
Thanks!!! It works like a charm!

**Comment by NyakudyaA** [comment]
@troyliu0105 How are you running this in Kubernetes with the job scheduler? Trying to implement the same but if I run the backup script directly it doesn't find all the envs

**Comment by troyliu0105** [comment]
@NyakudyaA sorry for the delay. You should build the docker image yourself. The image in the author's repo is not newest.

**Comment by NyakudyaA** [comment]
@troyliu0105 The image has been updated. I meant how do you run it in Kubernetes because it requires `/backup-scripts/pgenv.sh` which is only activated in start.sh
