### ISSUE TITLE
How to restore all backup's

### ISSUE THREAD

**Issue by cchalifo999** [kartoza/docker-pg-backup#79]
How to restore all backup's

**Comment by NyakudyaA** [comment]
Currently there is no native function that does this but that should be an easy one to do since we can loop through the backups extract the db name and use the corresponding archive.

For now you might be better off using a custom bash script

**Comment by cchalifo999** [comment]
> Currently there is no native function that does this but that should be an easy one to do since we can loop through the backups extract the db name and use the corresponding archive.
> 
> For now you might be better off using a custom bash script
ty
