### ISSUE TITLE
Add possbility to use Docker secrets 

### ISSUE THREAD

**Issue by LuViKu** [kartoza/docker-pg-backup#82]
The kartoza postgis docker compose allows the usage of e.g. POSTGRES_PASS_FILE in order to pass secrets into the container. It would be nice to be able to provide secret credentials to the docker-pg-backup image via the same way.

**Comment by NyakudyaA** [comment]
Can you do that already, I thought this is already possible https://github.com/kartoza/docker-pg-backup/blob/master/scripts/start.sh#L70

**Comment by LuViKu** [comment]
Sorry my bad. I totally missed the part of the start.sh script. I think it would be helpful to include this in the readme as well. Once I have time I can update the readme and create a pull request, if that would help you guys out.

Anyway thanks for the awesome repo! Have a good one.

**Comment by NyakudyaA** [comment]
PR are always welcome
