### ISSUE TITLE
The container is increasing memory consumption over time reaching to Gigabytes

### ISSUE THREAD

**Issue by YuryHrytsuk** [kartoza/docker-pg-backup#85]
### What is the bug or the crash?
`pg_backup` container uses increasingly more memory over time reaching to Gigabytes.
![image (1)](https://github.com/kartoza/docker-pg-backup/assets/50014626/3927e86b-c756-481d-b441-16ea3b36eed5)

### Steps to reproduce the issue

1. Start pg_backup as a docker swarm service
2. Keep pg_backup running for a month
3. Check memory usage pattern over this monthly period

### Versions

14-3.3

### Additional context

We run pg_bakcup within docker swarm  and use volumes to store backups

**Comment by NyakudyaA** [comment]
@YuryHrytsuk Have you tried to limit the memory using https://phoenixnap.com/kb/docker-memory-and-cpu-limit

**Comment by YuryHrytsuk** [comment]
> @YuryHrytsuk Have you tried to limit the memory using https://phoenixnap.com/kb/docker-memory-and-cpu-limit

This will kill the container (exit_code 137). Since the memory consumption jumps at around 11:00 PM (i.e. during the backup being made) I am afraid we will loose a backup. Any limit will lead to enforced restart (less or more often depending on how big is the limit)

I'd also like to point out again that every memory consumption leap happens during the backup being made. Perhaps, it will help to understand what is the problem

**Comment by NyakudyaA** [comment]
How big are your database dumps, Maybe you could manually execute the container and run the following
```
free -m
/backups.sh
free -m
```
This should give an indication of whether the memory is released after executing the script or not. If the memory is not being releases we might need to find a way to clear the memory cache inside the container

**Comment by YuryHrytsuk** [comment]
> How big are your database dumps, Maybe you could manually execute the container and run the following
> 
> ```
> free -m
> /backups.sh
> free -m
> ```
> 
> This should give an indication of whether the memory is released after executing the script or not. If the memory is not being releases we might need to find a way to clear the memory cache inside the container

![image](https://github.com/kartoza/docker-pg-backup/assets/50014626/33d24173-d8ad-4e8e-9840-820f68b6c1c6)
![image](https://github.com/kartoza/docker-pg-backup/assets/50014626/ddf599a3-0d3a-4a96-a1f4-17c85774f4db)

**Comment by YuryHrytsuk** [comment]
> How big are your database dumps, Maybe you could manually execute the container and run the following
> 
> ```
> free -m
> /backups.sh
> free -m
> ```
> 
> This should give an indication of whether the memory is released after executing the script or not. If the memory is not being releases we might need to find a way to clear the memory cache inside the container

Here we go
```bash
# free -mh
               total        used        free      shared  buff/cache   available
Mem:            31Gi        12Gi       1.4Gi       257Mi        17Gi        18Gi
Swap:             0B          0B          0B

# ./backups.sh 

# free -mh
               total        used        free      shared  buff/cache   available
Mem:            31Gi        12Gi       1.3Gi       257Mi        17Gi        18Gi
Swap:             0B          0B          0B
```

![image](https://github.com/kartoza/docker-pg-backup/assets/50014626/7deedcfa-c936-4699-a705-908461b78d7c)

**Comment by YuryHrytsuk** [comment]
I executed the `free` command again in ~30 mins just in case

```bash
$free -mh
               total        used        free      shared  buff/cache   available
Mem:            31Gi        12Gi       1.6Gi       257Mi        17Gi        18Gi
Swap:             0B          0B          0B
```

![image](https://github.com/kartoza/docker-pg-backup/assets/50014626/c664ff82-51ba-43dd-b29b-3d0b7f78428f)

**Comment by YuryHrytsuk** [comment]
Well, I apologize but the output of `free` command apparently does not make sense since it shows memory of the whole machine. However, Prometheus `container_memory_usage_bytes` metric still points to memory consumption increase

**Comment by YuryHrytsuk** [comment]
@NyakudyaA any updates on this matter?

**Comment by YuryHrytsuk** [comment]
My bad. Our backups indeed caused the memory increase
